use_frameworks!

platform :ios, '8.0'

target 'Nunchakus_Example' do
  pod 'Nunchakus', :path => '../'

  target 'Nunchakus_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
